export interface TutelasConfig {
  idSiproj: boolean;
  nroTutela: boolean;
  tipo: boolean;
  fecha: boolean;
  radicado: boolean;
  demandanteId: boolean;
  demandante: boolean;
  demandado: boolean;
  temaTutela: boolean;
  derechoVulnerado: boolean;
  extranjero: boolean;
  concepto: boolean;
  termino: boolean;
  remite: boolean;
  abogado: boolean;
  fechaVencimiento: boolean;
  fechaRespuesta: boolean;
  radicadoSalida: boolean;
  validacionRespuesta: boolean;
  oficioAdicional: boolean;
  fallo1raInst: boolean;
  fechaFallo1raInst: boolean;
  observacionFallo1raInst: boolean;
  terminoCumplimiento1raInst: boolean;
  cumplimiento1raInst: boolean;
  fechaCumplimiento1raInst: boolean;
  impugnacionSDP: boolean;
  fechaImpugnacion: boolean;
  fallo2daInst: boolean;
  fechaFallo2daInst: boolean;
  observacionFallo2daInst: boolean;
  terminoCumplimiento2daInst: boolean;
  cumplimiento2daInst: boolean;
  fechaCumplimiento2daInst: boolean;
  incidenteDesacato: boolean;
  observacionesGenerales: boolean;
}

export const initTutelasConfig = (): TutelasConfig => ({
  idSiproj: false,
  nroTutela: false,
  tipo: false,
  fecha: false,
  radicado: false,
  demandanteId: false,
  demandante: false,
  demandado: false,
  temaTutela: false,
  derechoVulnerado: false,
  extranjero: false,
  concepto: false,
  termino: false,
  remite: false,
  abogado: false,
  fechaVencimiento: false,
  fechaRespuesta: false,
  radicadoSalida: false,
  validacionRespuesta: false,
  oficioAdicional: false,
  fallo1raInst: false,
  fechaFallo1raInst: false,
  observacionFallo1raInst: false,
  terminoCumplimiento1raInst: false,
  cumplimiento1raInst: false,
  fechaCumplimiento1raInst: false,
  impugnacionSDP: false,
  fechaImpugnacion: false,
  fallo2daInst: false,
  fechaFallo2daInst: false,
  observacionFallo2daInst: false,
  terminoCumplimiento2daInst: false,
  cumplimiento2daInst: false,
  fechaCumplimiento2daInst: false,
  incidenteDesacato: false,
  observacionesGenerales: false,
});
