export interface ProcessesConfig {
  apoderadoActual: boolean;
  apoderadoAnterior: boolean;
  idSiproj: boolean;
  procesoAltoImpacto: boolean;
  radRamaJudicialInicial: boolean;
  radRamaJudicialActual: boolean;
  tipoProceso: boolean;
  diasTerminoContestacion: boolean;
  fechaNotificacion: boolean;
  fechaAdmision: boolean;
  fechaContestacion: boolean;
  fechaLimiteProbContestacion: boolean;
  validacionContestacion: boolean;
  calidadActuacionEntidad: boolean;
  demandados: boolean;
  idDemanante: boolean;
  demandante: boolean;
  despachoInicial: boolean;
  despachoActual: boolean;
  posicionSDP: boolean;
  temaGeneral: boolean;
  pretensionAsunto: boolean;
  cuantiaEstimada: boolean;
  valorPretensionesSMLVM: boolean;
  instanciaProceso: boolean;
  fechaProceso: boolean;
  ultimoEstadoProceso: boolean;
  etapaProcesal: boolean;
  fechaFalloPrimeraInstancia: boolean;
  sentidoFalloPrimeraInstancia: boolean;
  resumenPrimeraInstancia: boolean;
  fechaPresentacionRecurso: boolean;
  fechaFalloSegundaInstancia: boolean;
  sentidoFalloSegundaInstancia: boolean;
  resumenSegundaInstancia: boolean;
  incidente: boolean;
  estadoIncidente: boolean;
  resumenIncidente: boolean;
  observaciones: boolean;
  calificacionContingente: boolean;
  estado: boolean;
  fechaEjecutoria: boolean;
  fechaTerminacion: boolean;
  check: {
    date: Date;
    value: boolean;
    changeId: number[];
  };
}

export const initProcessesConfig = (): ProcessesConfig => ({
  apoderadoActual: false,
  apoderadoAnterior: false,
  idSiproj: false,
  procesoAltoImpacto: false,
  radRamaJudicialInicial: false,
  radRamaJudicialActual: false,
  tipoProceso: false,
  diasTerminoContestacion: false,
  fechaNotificacion: false,
  fechaAdmision: false,
  fechaContestacion: false,
  fechaLimiteProbContestacion: false,
  validacionContestacion: false,
  calidadActuacionEntidad: false,
  demandados: false,
  idDemanante: false,
  demandante: false,
  despachoInicial: false,
  despachoActual: false,
  posicionSDP: false,
  temaGeneral: false,
  pretensionAsunto: false,
  cuantiaEstimada: false,
  valorPretensionesSMLVM: false,
  instanciaProceso: false,
  fechaProceso: false,
  ultimoEstadoProceso: false,
  etapaProcesal: false,
  fechaFalloPrimeraInstancia: false,
  sentidoFalloPrimeraInstancia: false,
  resumenPrimeraInstancia: false,
  fechaPresentacionRecurso: false,
  fechaFalloSegundaInstancia: false,
  sentidoFalloSegundaInstancia: false,
  resumenSegundaInstancia: false,
  incidente: false,
  estadoIncidente: false,
  resumenIncidente: false,
  observaciones: false,
  calificacionContingente: false,
  estado: false,
  fechaEjecutoria: false,
  fechaTerminacion: false,
  check: {
    date: new Date(),
    value: true,
    changeId: [],
  },
});
